sql_training_completed_exercises
AleksandrsVerenkovs/SQL_training pull request #1
Opened 2021-09-09 20:46 UTC by AleksandrsVerenkovs

2021-09-10 16:08 UTC, ausmoons requested changes

2021-09-10 16:08 UTC, ausmoons commented on sql-movies/test/05-insert-relationship-data.test.ts
> +      expect(count.c).toBe(2499); //3340
Kāpec mainīji testa sagaidāmo rezultātu?

2021-09-11 09:22 UTC, AleksandrsVerenkovs commented on sql-movies/test/05-insert-relationship-data.test.ts
> +      expect(count.c).toBe(2499); //3340
Jo pēc pirmajiem 3 testiem, man atgriež 2499 režisoru ierakstus.
Edit: padevu ne to tabulu. Izlabošu :)

2021-09-11 18:59 UTC, ausmoons approved these changes

2021-09-11 18:59 UTC, ausmoons commented on sql-movies/test/05-insert-relationship-data.test.ts
> +      expect(count.c).toBe(3340); //3340
Lieks komentārs

2021-09-12 10:25 UTC, merged